Repository parley-messaging/android-library, pull requests merged in 2024-05, with the labels that each got.

#39 add possibility to disable default push permission dialog and channel…
  parley/src/main/java/nu/parley/android/Parley.java
  parley/src/main/java/nu/parley/android/view/ParleyView.java
Labels: in progress

#40 Prevent NPE for call parleyErrorResponse.getNotification
  parley/src/main/java/nu/parley/android/data/net/response/ParleyErrorResponse.java
Labels: ready

#48 Fixed info shadow showing unwantedly
  parley/src/main/java/nu/parley/android/view/BalloonView.java
Labels: ready

#46 Add new certificate for 2024 -> 2025
  parley/src/main/res/xml/parley_network_security_config.xml
Labels: ready

#49 Add new function to remove all local user data;
  parley/src/main/java/nu/parley/android/Parley.java
Labels: enhancement, ready
